name: NysxlBountySystem
main: org.Nysxl.BountySystem.NysxlBountySystem
version: 1.0-SNAPSHOT
author: Nysxl
description: A plugin for managing a bounty system with dependencies on NysxlServerUtils and Vault.

depend:
  - NysxlServerUtils
  - Vault

api-version: 1.20

commands:
  bounty:
    description: Manage bounties
    usage: /bounty <open|set <player> <amount>>
    permission: bounty.manage
    permission-message: You do not have permission to execute this command.